### ISSUE TITLE
question(base): where does the base come from?

### ISSUE THREAD

**Issue by Kristinita** [e2yo/eyo-kernel#20]
### 1. Кратко

В описаниях к eyo и eyo-kernel я не нашёл информации, откуда взята [**база**](https://github.com/hcodes/eyo-kernel/tree/master/dict_src). Неплохо было бы добавить эту информацию.

#### 2.1. Престиж проекта

Лично у меня бы было больше доверия к базе, основанной на авторитетных источниках, нежели к взятой непонятно откуда. Возможно, специалисты по русскому языку могут разделить такое мнение.

Если указать источники, повысится вероятность, что профессионалы будут считаться с Вашим проектом, ссылаться на него и заинтересованы в сотрудничестве.

#### 2.2. Привлечение к разработке базы

Судя по **#24**, база нуждается в совершенствовании. Например, на основании следующих источников:

+ [**cловарь употребления буквы ё**](http://www.yomaker.ru/yoslovar.htm),
+ [**база слов с буквой ё**](http://python.anabar.ru/yo.htm).

Положим, кто-то хочет улучшить базу или удастся привлечь к работе над проектом энтузиастов буквы «ё» (раз [**здесь**](http://python.anabar.ru/yo.htm) столько людей принимало участие, при правильном подходе и на eyo вполне могут согласиться). Но не зная, какие источники и какой степени авторитетности использованы, больше шансов, что эти люди оставят планы помощи Вашему проекту, поскольку труднее понять, с чего начинать и какого именно рода деятельностью заниматься. Если и нет, они будут повторяться, начиная использовать те же источники, на которых строилась база.

Чем подробнее будет расписано, что задействовано в базе, тем меньше дополнительной работы будет потенциальным помощникам в работе над eyo.

Спасибо.

**Comment by hcodes** [comment]
https://github.com/e2yo/eyo-kernel#%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C
