### ISSUE TITLE
feature_request(enhancement): custom exceptions

### ISSUE THREAD

**Issue by Kristinita** [e2yo/eyo-kernel#23]
### 1. Summary

Неплохо было бы, если б пользователь мог применять собственные исключения.

### 2. Аргументация

Как видно из **#24**, eyo работает не идеально и требует улучшений. я понимаю, что eyo — это open source проект, и разработчик не обязан бежать моментально исправлять каждую мелочь. Но для пользователей большое время ожидания может оказаться нежелательным, поскольку они могут получать ошибки в билдах.

Поэтому предлагаю дать возможность пользователям использовать собственные файлы исключений, чтобы не ждать, пока у разработчика появятся время и желание на доработку.

#### 3.1. Файл

+ `eyo.yaml`:

```yaml
exclude: 'недреманное'
exclude: 'призрак, иль еще'
```

+ Пояснения:

1. [**НедрЕма&#x301;нное око**](http://orf.textologia.ru/definit/nedremannoe-oko/?q=532&n=74728).
1. > Ничтожный призрак, иль еще

   > Москвич в Гарольдовом плаще,

    Конкретно в данном контексте — [**строки из Евгения Онегина**](http://pushkin-lit.ru/pushkin/text/evgenij-onegin/onegin_7.htm) — необходимо писать «ещЕ&#x301;».

#### 3.2. Шаги для воспроизведения

Пользователь вводит в терминале:

    eyo KiraExample.txt --excludes

→ eyo не реагирует на `недрЕманное` и `призрак, иль еще` в файле `KiraExample.txt`.

Спасибо.

**Comment by hcodes** [comment]
https://github.com/e2yo/eyo-kernel/issues/15
